title: Calvin Chee # your name (or website title) here
logo: <"/images/Profilephoto1.jpg" width="100" height="200"> # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)

  <br><br>
  
  A reliable and accountable tourism & hospitality professional, with an aim to establish a career as a data analyst, to provide valuable data-driven insights to organisations. 
  
  <br><br>
  
  A strong team player and independent individual with a proven track record in outstanding work performance, teamwork,  communications & management skills, with testimonies & awards from multiple organizations, striving to provide outstanding value to the company.
  
  <br><br>
  
  <a href="https://www.linkedin.com/in/calvin-chee/">View My LinkedIn Profile</a> 
 
  <br><br>
    
