title: Calvin Chee # your name (or website title) here
logo: <"images/Profilephoto1.jpg" height=790> # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)

  <br><br>
  
  An independent individual and strong team player, with an aim to establish a career as a data analyst, to provide valuable data-driven insights to organisations. 
  
  <br><br>
  
  <a href="https://www.linkedin.com/in/calvin-chee/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
